version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11.5-management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always